# Generated by Django 3.0 on 2019-12-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('footer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text_en', models.CharField(max_length=250, unique=True, verbose_name='Footer Text')),
                ('footer_text_ar', models.CharField(max_length=250, null=True, unique=True, verbose_name='Footer Arab Text')),
                ('footer_year', models.CharField(max_length=250, null=True, unique=True, verbose_name='Footer Year')),
                ('footer_version', models.CharField(max_length=250, unique=True, verbose_name='Footer Version')),
                ('footer_address_en', models.CharField(max_length=1024, unique=True, verbose_name='Footer Address')),
                ('footer_address_ar', models.CharField(max_length=1024, unique=True, verbose_name='Footer Arab Address')),
                ('footer_logo', models.ImageField(upload_to='media/site/images/')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
                'ordering': ['footer_id'],
            },
        ),
        migrations.CreateModel(
            name='main_site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_en', models.CharField(max_length=250, unique=True, verbose_name='Site Name')),
                ('site_short_name_en', models.CharField(max_length=100, unique=True, verbose_name='Site Short Name')),
                ('site_name_ar', models.CharField(max_length=250, unique=True, verbose_name='Site Arabic Name')),
                ('site_short_name_ar', models.CharField(max_length=100, unique=True, verbose_name='Site Short Arabic Name')),
                ('site_name_link', models.CharField(max_length=250, unique=True, verbose_name='Site Name link')),
                ('site_logo', models.ImageField(upload_to='media/site/images/')),
            ],
            options={
                'verbose_name': 'Main Site',
                'verbose_name_plural': 'Main Site',
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name_en', models.CharField(max_length=250, unique=True, verbose_name='Site Name')),
                ('menu_link', models.CharField(max_length=250, null=True, unique=True, verbose_name='Site Name')),
                ('menu_order', models.IntegerField(verbose_name='Menu Order')),
                ('menu_name_ar', models.CharField(max_length=250, unique=True, verbose_name='Site Name')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['menu_order'],
            },
        ),
        migrations.CreateModel(
            name='menu_box',
            fields=[
                ('menu_box_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_box_name', models.CharField(max_length=250, unique=True, verbose_name='Menu Box Name')),
                ('menu_box_name_ar', models.CharField(max_length=250, unique=True, verbose_name='Menu Box Arabic Name')),
                ('menu_box_logo', models.ImageField(upload_to='media/site/images/')),
                ('menu_box_order', models.IntegerField(verbose_name='Menu Box Order')),
            ],
            options={
                'verbose_name': 'Menu Box',
                'verbose_name_plural': 'Menu Boxes',
                'ordering': ['menu_box_order'],
            },
        ),
        migrations.CreateModel(
            name='menu_box_item',
            fields=[
                ('menu_box_item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_box_item_name', models.CharField(max_length=250, unique=True, verbose_name='Menu Box Item Name')),
                ('menu_box_item_name_ar', models.CharField(max_length=250, unique=True, verbose_name='Menu Box Item Arabic Name')),
                ('menu_box_item_logo', models.ImageField(upload_to='media/site/images/')),
                ('menu_box_item_order', models.IntegerField(verbose_name='Menu Box Item Order')),
                ('menu_box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='_web.menu_box')),
            ],
            options={
                'verbose_name': 'Menu Box Item',
                'verbose_name_plural': 'Menu Box Items',
                'ordering': ['menu_box_item_order'],
            },
        ),
        migrations.AddIndex(
            model_name='menu_box',
            index=models.Index(fields=['menu_box_name'], name='Dweb_menu_b_menu_bo_659cc4_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box',
            index=models.Index(fields=['menu_box_name_ar'], name='Dweb_menu_b_menu_bo_29bb38_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box',
            index=models.Index(fields=['menu_box_order'], name='Dweb_menu_b_menu_bo_6bae76_idx'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_super_menu',
            field=models.ForeignKey(limit_choices_to={'isRootMenu': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='_web.menu'),
        ),
        migrations.AddIndex(
            model_name='main_site',
            index=models.Index(fields=['site_name_en'], name='Dweb_main_s_site_na_4de4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='main_site',
            index=models.Index(fields=['site_short_name_en'], name='Dweb_main_s_site_sh_ec7d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='main_site',
            index=models.Index(fields=['site_name_ar'], name='Dweb_main_s_site_na_c9c19a_idx'),
        ),
        migrations.AddIndex(
            model_name='main_site',
            index=models.Index(fields=['site_short_name_ar'], name='Dweb_main_s_site_sh_bcaab7_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_text_en'], name='Dweb_footer_footer__4ac302_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_text_ar'], name='Dweb_footer_footer__531255_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_year'], name='Dweb_footer_footer__cc2717_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_version'], name='Dweb_footer_footer__76bf56_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_address_en'], name='Dweb_footer_footer__b22ade_idx'),
        ),
        migrations.AddIndex(
            model_name='footer',
            index=models.Index(fields=['footer_address_ar'], name='Dweb_footer_footer__5c51ab_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box_item',
            index=models.Index(fields=['menu_box_item_name'], name='Dweb_menu_b_menu_bo_43c73b_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box_item',
            index=models.Index(fields=['menu_box_item_name_ar'], name='Dweb_menu_b_menu_bo_b6236c_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box_item',
            index=models.Index(fields=['menu_box_item_order'], name='Dweb_menu_b_menu_bo_a98852_idx'),
        ),
        migrations.AddIndex(
            model_name='menu_box_item',
            index=models.Index(fields=['menu_box'], name='Dweb_menu_b_menu_bo_a12027_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_name_en'], name='Dweb_menu_menu_na_84861b_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_link'], name='Dweb_menu_menu_li_c42e09_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_order'], name='Dweb_menu_menu_or_eefc63_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_super_menu'], name='Dweb_menu_menu_su_e1baa3_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['menu_name_ar'], name='Dweb_menu_menu_na_d3700c_idx'),
        ),
    ]
