# Generated by Django 3.0 on 2019-12-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu_box_item',
            options={'ordering': ['menu_box', 'menu_box_item_order'], 'verbose_name': 'Menu Box Item', 'verbose_name_plural': 'Menu Box Items'},
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_isRootMenu',
            field=models.BooleanField(default=True, verbose_name='is Root Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Menu Link'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name_ar',
            field=models.CharField(max_length=250, unique=True, verbose_name='Menu Arabic Name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name_en',
            field=models.CharField(max_length=250, unique=True, verbose_name='Menu Name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_order',
            field=models.IntegerField(unique=True, verbose_name='Menu Order'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_super_menu',
            field=models.ForeignKey(blank=True, limit_choices_to={'menu_isRootMenu': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='_web.menu'),
        ),
        migrations.AlterField(
            model_name='menu_box',
            name='menu_box_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/site/images/'),
        ),
    ]
