# Generated by Django 3.0 on 2019-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0003_menu_box_item_menu_box_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_link',
            field=models.CharField(max_length=250, null=True, verbose_name='Menu Link'),
        ),
    ]
