# Generated by Django 3.0 on 2019-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0004_auto_20191213_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_box_item',
            name='menu_box_item_logo',
        ),
        migrations.AddField(
            model_name='menu_box_item',
            name='menu_box_item_fontawesome',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Menu Box Item fontawesome'),
        ),
    ]
