# Generated by Django 3.0 on 2019-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_web', '0005_auto_20191215_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_fontawesome',
            field=models.CharField(blank=True, help_text='get Images form https://fontawesome.com/icons?m=free', max_length=250, null=True, verbose_name='Menu Box Item fontawesome'),
        ),
        migrations.AlterField(
            model_name='menu_box_item',
            name='menu_box_item_fontawesome',
            field=models.CharField(blank=True, help_text='get Images form https://fontawesome.com/icons?m=free', max_length=250, null=True, verbose_name='Menu Box Item fontawesome'),
        ),
    ]
