# Generated by Django 3.2.6 on 2021-08-07 07:25

import _data._data_quality
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_cfi',
            name='report_cfi',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=_data._data_quality.get_upload_file_name, validators=[_data._data_quality.validate_file_size, _data._data_quality.validate_file_type], verbose_name='Course File Index'),
        ),
        migrations.AddField(
            model_name='course_cfi',
            name='report_cfr',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=_data._data_quality.get_upload_file_name, validators=[_data._data_quality.validate_file_size, _data._data_quality.validate_file_type], verbose_name='Course File Report'),
        ),
    ]
