# Generated by Django 3.2.6 on 2021-08-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0003_auto_20210808_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityexportfile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_data.department'),
        ),
        migrations.AddField(
            model_name='qualityexportfile',
            name='quality_type',
            field=models.TextField(default='', verbose_name='Quality Type'),
        ),
    ]
