# Generated by Django 3.2.6 on 2021-08-14 07:42

import _data._data_quality
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0004_auto_20210811_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_cfi',
            name='exams_samples_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=_data._data_quality.get_upload_file_name, validators=[_data._data_quality.validate_file_size_50, _data._data_quality.validate_file_type], verbose_name='Exams Samples File'),
        ),
    ]
