# Generated by Django 3.2.10 on 2021-12-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0005_alter_course_cfi_exams_samples_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('email_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Email ID')),
                ('email_sender', models.CharField(max_length=250, verbose_name='Email Sender')),
                ('email_receiver', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email Receiver')),
                ('email_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Email Title')),
                ('email_message', models.CharField(max_length=4096, verbose_name='Email Message')),
                ('sending_time', models.DateTimeField(auto_now=True, verbose_name='Sending time')),
                ('sending_state', models.CharField(default='-1', max_length=1, verbose_name='Email Status')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['email_receiver', 'sending_time'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_sender'], name='Ddata_email_email_s_6744b3_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['email_receiver'], name='Ddata_email_email_r_c21ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sending_state'], name='Ddata_email_sending_237311_idx'),
        ),
    ]
