# Generated by Django 3.2.10 on 2021-12-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0006_auto_20211227_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_sender',
            field=models.CharField(default='tanomah.quality@gmail.com', max_length=250, verbose_name='Email Sender'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sending_state',
            field=models.CharField(default='Created', max_length=64, verbose_name='Email Status'),
        ),
    ]
