# Generated by Django 3.2.10 on 2022-01-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0009_auto_20220126_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentfile',
            name='means_high',
            field=models.TextField(blank=True, null=True, verbose_name='means_high'),
        ),
        migrations.AddField(
            model_name='departmentfile',
            name='means_low',
            field=models.TextField(blank=True, null=True, verbose_name='means_low'),
        ),
    ]
