# Generated by Django 3.2.10 on 2022-05-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_data', '0011_alter_semester_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_sender',
            field=models.CharField(default='medzarka@gmail.com', max_length=250, verbose_name='Email Sender'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sending_state',
            field=models.CharField(default='Created', max_length=2048, verbose_name='Email Status'),
        ),
    ]
