"""
Django settings for uKKU2 project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import sys
from pathlib import Path
import environ
import os


def createDir(dirname):
    try:
        os.makedirs(dirname)
    except FileExistsError:
        pass


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    env_filename = os.getenv('env_filename')
    print(f'Configuration Site in file {env_filename}.')
except:
    env_filename = '.env'
    print(f'Configuration Site in file "site_conf".')

if env_filename is None:
    print(f'The env filename "env_filename" is not set !')
    sys.exit(-1)

if not os.path.exists(os.path.join(BASE_DIR, env_filename)):
    print(f'The env filename {env_filename} does not exists!')
    sys.exit(-1)

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    SITE_DATA_PATH=(str, 'data'),
    SESSION_EXPIRE_AT_BROWSER_CLOSE=(bool, False),
    SESSION_COOKIE_AGE=(int, 3600),
    FILE_UPLOAD_MAX_MEMORY_SIZE=(int, 104857600),
    SESSION_COOKIE_SECURE=(bool, True),
    CSRF_COOKIE_SECURE=(bool, True),
    SECURE_SSL_REDIRECT=(bool, True),
    SECURE_HSTS_SECONDS=(int, 2592000),
    SECURE_HSTS_INCLUDE_SUBDOMAINS=(bool, True),
    SECURE_HSTS_PRELOAD=(bool, True),
    SITE_ADMIN_TEMPLATE=(str, 'GRAPPELLI'),
    SITE_ADMIN_SITE_TITLE=(str, 'uKKU2 Quality Document Manager'),
    SITE_ADMIN_SITE_HEADER=(str, 'uKKU (ver.2) Admin'),
    SITE_ADMIN_SITE_INDEX_TITLE=(str, 'Welcome to uKKU2 Admin'),
)
env.read_env(os.path.join(BASE_DIR, env_filename))
##" https://github.com/medzarka/uKKU2.git


DATA_DIR = os.path.join(os.environ['HOME'], env('SITE_DATA_PATH'))
createDir(DATA_DIR)
print(f'[DIR] the base dir is {BASE_DIR}')
print(f'[DIR] the data dir is {DATA_DIR}')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', env.str('SITE_URL')]

# Application definition
INSTALLED_APPS = []
if env.str('SITE_ADMIN_TEMPLATE') == 'GRAPPELLI':
    INSTALLED_APPS = ['grappelli', ]
if env.str('SITE_ADMIN_TEMPLATE') == 'ADMIN_INTERFACE':
    INSTALLED_APPS = ['admin_interface',
                      'colorfield', ]

INSTALLED_APPS += [

    'import_export',
    'dbbackup',  # django-dbbackup
    'django_db_logger',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    '_data.apps.DataConfig',
    '_web.apps.WebConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uKKU2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uKKU2.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
# }

if env.str('DATABASE_URL', default=''):
    DATABASES = {
        'default': env.db(),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATA_DIR.path('db')('django.sqlite3'),
        },
    }


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

#CACHES = {
#    # The cache() method is an alias for cache_url().
#    'default': env.cache(),
#}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
####### Translation config
# createDir(os.path.join(DATA_DIR, 'locale'))
# LOCALE_PATHS = [os.path.join(DATA_DIR, 'locale')]
# LANGUAGE_CODE = 'en'
# LANGUAGES = [
#    ('en', 'English'),
#    ('ar', 'Arabic'),
# ]
# print(f'[DIR] the localisation file is in {os.path.join(DATA_DIR, "locale")}')

TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

####### Media and Static files


createDir(os.path.join(DATA_DIR, 'static'))
createDir(os.path.join(DATA_DIR, 'media'))
STATIC_ROOT = os.path.join(os.path.join(DATA_DIR, 'static'))
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
MEDIA_ROOT = os.path.join(os.path.join(DATA_DIR, 'media'))
MEDIA_URL = '/media/'
print(f'[DIR] the static files are in {os.path.join(DATA_DIR, "static")}')
print(f'[DIR] the media files are in {os.path.join(DATA_DIR, "media")}')

###### Login & Session Age
# LOGIN_URL = '/web/login/'
# LOGIN_REDIRECT_URL = '/web/dashboard'
# AUTH_USER_MODEL = '_data.User'
# AUTH_LOGIN_URL = 'web_auth_login'
# AUTH_LOGOUT_URL = 'web_auth_logout'
# AUTH_DASHBOARD_URL = 'web_dashboard'
LOGIN_URL = '/web/login/'
LOGIN_REDIRECT_URL = '/web/dashboard'
# print(f'[AUTH] the class {AUTH_USER_MODEL} is used as users backend.')

###### Session management. The session will close after
SESSION_EXPIRE_AT_BROWSER_CLOSE = env.bool('SESSION_EXPIRE_AT_BROWSER_CLOSE')
SESSION_COOKIE_AGE = env.int('SESSION_COOKIE_AGE')
print(f'[Sessions] the maximum time to keep the session cookie is {SESSION_COOKIE_AGE / 60} minute(s).')

###### allow upload big file
FILE_UPLOAD_MAX_MEMORY_SIZE = env.int('FILE_UPLOAD_MAX_MEMORY_SIZE')
print(f'[FILES] the maximum size for file upload is  {FILE_UPLOAD_MAX_MEMORY_SIZE / (1024 * 1024)} MBytes.')

###### SSL Session
SESSION_COOKIE_SECURE = env.str('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = env.str('CSRF_COOKIE_SECURE')
SECURE_SSL_REDIRECT = env.str('SECURE_SSL_REDIRECT')

SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS')
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS')
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD')

###### Loggin
createDir(os.path.join(DATA_DIR, 'log'))
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'db_log': {
            'level': 'DEBUG',
            'class': 'django_db_logger.db_log_handler.DatabaseLogHandler'
        },
    },
    'loggers': {
        'db': {
            'handlers': ['db_log'],
            'level': 'DEBUG'
        },
        'django.request': {  # logging 500 errors to database
            'handlers': ['db_log'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}
DJANGO_DB_LOGGER_ENABLE_FORMATTER = env.bool('DJANGO_DB_LOGGER_ENABLE_FORMATTER')
DJANGO_DB_LOGGER_ADMIN_LIST_PER_PAGE = env.int('DJANGO_DB_LOGGER_ADMIN_LIST_PER_PAGE')

print(f'[DIR] the log file is in {os.path.join(DATA_DIR, "log")}')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#######  Sending emails
# The email() method is an alias for email_url().
EMAIL_CONFIG = env.email(
    'EMAIL_URL',
    default='smtp://user:password@localhost:25'
)
vars().update(EMAIL_CONFIG)

# only if django version >= 3.0
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

##### Admin Title configuration
SITE_ADMIN_TEMPLATE = env.str('SITE_ADMIN_TEMPLATE')
GRAPPELLI_ADMIN_TITLE = env.str('SITE_ADMIN_SITE_TITLE')
ADMIN_SITE_SITE_HEADER = env.str('SITE_ADMIN_SITE_HEADER')
ADMIN_SITE_INDEX_TITLE = env.str('SITE_ADMIN_SITE_INDEX_TITLE')
ADMIN_SITE_SITE_TITLE = env.str('SITE_ADMIN_SITE_TITLE')

##### database and media backup
BACKUP_DIR = os.path.join(os.path.join(DATA_DIR, 'backup'))
createDir(BACKUP_DIR)
DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': BACKUP_DIR}
print(f'[DIR] the backup dir is {os.path.join(DATA_DIR, "backup")}')
